"""empty message

<<<<<<< HEAD:migrations/versions/1043170bcf70_.py
Revision ID: 1043170bcf70
Revises: 
Create Date: 2022-03-16 19:55:31.720754
=======
Revision ID: 1a4232f6b7f0
Revises: 
Create Date: 2022-03-16 20:01:17.084938
>>>>>>> 699e7d06a9a6b85d41ef4f1b2b5352ef49b34b73:migrations/versions/1a4232f6b7f0_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/1043170bcf70_.py
revision = '1043170bcf70'
=======
revision = '1a4232f6b7f0'
>>>>>>> 699e7d06a9a6b85d41ef4f1b2b5352ef49b34b73:migrations/versions/1a4232f6b7f0_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('usertype', sa.Enum('buyer', 'creator', name='UserTypes'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('project_type', sa.Enum('keycap', 'keyboard', 'switches', name='ProjectTypes'), nullable=False),
    sa.Column('project_stage', sa.Enum('interestcheck', 'groupbuy', 'ended', name='ProjectStage'), nullable=False),
    sa.Column('sale_type', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('baseprice', sa.Float(precision=8), nullable=True),
    sa.Column('estimated_ship', sa.String(length=120), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('vendor_links', sa.String(length=250), nullable=True),
    sa.Column('discussion_links', sa.String(length=250), nullable=True),
    sa.Column('img_url', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('projectid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectid'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracked')
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
