"""empty message

Revision ID: 20d5a00bb081
Revises: 2047698c0d56
Create Date: 2022-03-12 05:57:25.058939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d5a00bb081'
down_revision = '2047698c0d56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
