"""empty message

Revision ID: 3ec198e8acf1
Revises: f270d83714c4
Create Date: 2022-02-26 03:08:00.990803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec198e8acf1'
down_revision = 'f270d83714c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('img_url', sa.String(length=250), nullable=True))
    op.alter_column('project', 'baseprice',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)
    op.drop_column('project', 'img_url')
    # ### end Alembic commands ###
