"""empty message

Revision ID: 53ca7f27f7c0
Revises: d7e299f06aee
Create Date: 2022-03-17 06:51:08.697782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ca7f27f7c0'
down_revision = 'd7e299f06aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=10),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.Float(precision=10),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
