"""empty message

Revision ID: 80006e2c9880
Revises: c3cc31be6c0c
Create Date: 2022-03-03 02:03:41.807273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80006e2c9880'
down_revision = 'c3cc31be6c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
