"""empty message

<<<<<<< HEAD:migrations/versions/f2a912d4a5af_.py
Revision ID: f2a912d4a5af
Revises: 
Create Date: 2022-03-17 21:58:39.318496
=======
Revision ID: 946ec2d016d9
Revises: 
Create Date: 2022-03-17 21:43:52.340919
>>>>>>> a22bf67bd58ae4a4be729b8b9152a61185fd7cb5:migrations/versions/946ec2d016d9_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/f2a912d4a5af_.py
revision = 'f2a912d4a5af'
=======
revision = '946ec2d016d9'
>>>>>>> a22bf67bd58ae4a4be729b8b9152a61185fd7cb5:migrations/versions/946ec2d016d9_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('usertype', sa.Enum('buyer', 'creator', name='UserTypes'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('project_type', sa.Enum('keycap', 'keyboard', 'switches', name='ProjectTypes'), nullable=False),
    sa.Column('project_stage', sa.Enum('interestcheck', 'groupbuy', 'ended', name='ProjectStage'), nullable=False),
    sa.Column('sale_type', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('baseprice', sa.Float(precision=8), nullable=True),
    sa.Column('estimated_ship', sa.String(length=120), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('vendor_links', sa.String(length=250), nullable=True),
    sa.Column('discussion_links', sa.String(length=250), nullable=True),
    sa.Column('img_url', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('projectid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['projectid'], ['project.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tracked')
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
