"""empty message

Revision ID: c3cc31be6c0c
Revises: 3ec198e8acf1
Create Date: 2022-03-01 02:04:43.048078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cc31be6c0c'
down_revision = '3ec198e8acf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
    op.alter_column('tracked', 'userid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tracked', 'projectid',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tracked', 'projectid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tracked', 'userid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('project', 'baseprice',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
