"""empty message

Revision ID: d7e299f06aee
Revises: e8c20a535650
Create Date: 2022-03-17 06:03:28.791670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e299f06aee'
down_revision = 'e8c20a535650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=8),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'baseprice',
               existing_type=sa.Float(precision=8),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
